[theme]
base = "dark"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false[theme]
base="dark"

[server]
headless=true

[browser]
gatherUsageStats=false

[client]
showSidebarNavigation=false[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
